# Example patch for orchestrator deployment in staging
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
spec:
  template:
    spec:
      containers:
        - name: orchestrator
          image: ghcr.io/your-org/codex-orchestrator:staging
          resources:
            requests:
              cpu: "75m"
              memory: "96Mi"
            limits:
              cpu: "350m"
              memory: "384Mi"
