"""
GITHUB + VERCEL INTEGRATION PLAN
==================================
Complete implementation guide for automated Git + deployment workflows

Components:
1. GitHub repository creation
2. Git initialization and commit
3. Vercel project setup
4. Deployment trigger
5. Webhook notifications
"""

import os
import subprocess
import requests
from typing import Dict, Any, Optional
from pathlib import Path


class GitHubIntegration:
    """Handles GitHub repository creation and management"""
    
    def __init__(self, github_token: str, organization: str = "codexdominion"):
        """
        Initialize GitHub integration
        
        Args:
            github_token: GitHub Personal Access Token with repo scope
            organization: GitHub org name (or username for personal repos)
        """
        self.token = github_token
        self.org = organization
        self.base_url = "https://api.github.com"
        self.headers = {
            "Authorization": f"Bearer {github_token}",
            "Accept": "application/vnd.github.v3+json"
        }
    
    def create_repository(
        self, 
        repo_name: str, 
        description: str,
        private: bool = False
    ) -> Dict[str, Any]:
        """
        Create a new GitHub repository
        
        Args:
            repo_name: Repository name (will be slugified)
            description: Repository description
            private: Whether repo should be private
        
        Returns:
            repo_info: Dictionary with repo_url, clone_url, etc.
        """
        # Slugify repo name
        slug = repo_name.lower().replace(" ", "-").replace("_", "-")
        
        # Check if repo exists
        check_url = f"{self.base_url}/repos/{self.org}/{slug}"
        check_response = requests.get(check_url, headers=self.headers)
        
        if check_response.status_code == 200:
            print(f"✅ Repository {self.org}/{slug} already exists")
            return check_response.json()
        
        # Create new repository
        create_url = f"{self.base_url}/orgs/{self.org}/repos"
        payload = {
            "name": slug,
            "description": description,
            "private": private,
            "auto_init": False,  # We'll push initial commit ourselves
            "has_issues": True,
            "has_projects": False,
            "has_wiki": False
        }
        
        response = requests.post(create_url, headers=self.headers, json=payload)
        
        if response.status_code == 201:
            repo_data = response.json()
            print(f"✅ Created repository: {repo_data['html_url']}")
            return {
                "repo_name": repo_data["name"],
                "repo_url": repo_data["html_url"],
                "clone_url": repo_data["clone_url"],
                "ssh_url": repo_data["ssh_url"],
                "default_branch": repo_data["default_branch"]
            }
        else:
            raise Exception(f"Failed to create repo: {response.status_code} {response.text}")
    
    def initialize_and_push(
        self, 
        local_path: str, 
        repo_url: str,
        commit_message: str = "Initial commit - Generated by CodexDominion"
    ) -> bool:
        """
        Initialize git, commit all files, and push to GitHub
        
        Args:
            local_path: Path to project directory
            repo_url: GitHub repository URL (HTTPS or SSH)
            commit_message: Initial commit message
        
        Returns:
            success: True if push succeeded
        """
        try:
            # Change to project directory
            os.chdir(local_path)
            
            # Initialize git
            subprocess.run(["git", "init"], check=True)
            subprocess.run(["git", "branch", "-M", "main"], check=True)
            
            # Add all files
            subprocess.run(["git", "add", "."], check=True)
            
            # Commit
            subprocess.run([
                "git", "commit", "-m", commit_message,
                "--author", "CodexDominion Bot <bot@codexdominion.app>"
            ], check=True)
            
            # Add remote
            subprocess.run(["git", "remote", "add", "origin", repo_url], check=True)
            
            # Push
            subprocess.run(["git", "push", "-u", "origin", "main"], check=True)
            
            print(f"✅ Pushed to {repo_url}")
            return True
            
        except subprocess.CalledProcessError as e:
            print(f"❌ Git operation failed: {e}")
            return False


class VercelIntegration:
    """Handles Vercel deployment"""
    
    def __init__(self, vercel_token: str, team_id: Optional[str] = None):
        """
        Initialize Vercel integration
        
        Args:
            vercel_token: Vercel API token
            team_id: Vercel team ID (optional, for team deployments)
        """
        self.token = vercel_token
        self.team_id = team_id
        self.base_url = "https://api.vercel.com"
        self.headers = {
            "Authorization": f"Bearer {vercel_token}",
            "Content-Type": "application/json"
        }
    
    def create_project(
        self,
        project_name: str,
        github_repo: str,
        framework: str = "nextjs"
    ) -> Dict[str, Any]:
        """
        Create a new Vercel project linked to GitHub repo
        
        Args:
            project_name: Vercel project name
            github_repo: GitHub repo in format "org/repo"
            framework: Framework type (nextjs, vite, etc.)
        
        Returns:
            project_info: Dictionary with project ID, URL, etc.
        """
        url = f"{self.base_url}/v10/projects"
        if self.team_id:
            url += f"?teamId={self.team_id}"
        
        payload = {
            "name": project_name,
            "framework": framework,
            "gitRepository": {
                "type": "github",
                "repo": github_repo
            },
            "buildCommand": "npm run build",
            "outputDirectory": "out",
            "installCommand": "npm install",
            "devCommand": "npm run dev"
        }
        
        response = requests.post(url, headers=self.headers, json=payload)
        
        if response.status_code in [200, 201]:
            project_data = response.json()
            print(f"✅ Created Vercel project: {project_name}")
            return {
                "project_id": project_data["id"],
                "project_name": project_data["name"],
                "project_url": f"https://{project_data['name']}.vercel.app"
            }
        else:
            raise Exception(f"Failed to create Vercel project: {response.status_code} {response.text}")
    
    def trigger_deployment(
        self,
        project_name: str,
        production: bool = True
    ) -> Dict[str, Any]:
        """
        Trigger a new deployment
        
        Args:
            project_name: Vercel project name
            production: Deploy to production (vs preview)
        
        Returns:
            deployment_info: Dictionary with deployment URL, ID, status
        """
        url = f"{self.base_url}/v13/deployments"
        if self.team_id:
            url += f"?teamId={self.team_id}"
        
        payload = {
            "name": project_name,
            "target": "production" if production else "preview",
            "gitSource": {
                "type": "github",
                "ref": "main"
            }
        }
        
        response = requests.post(url, headers=self.headers, json=payload)
        
        if response.status_code in [200, 201]:
            deployment_data = response.json()
            deployment_url = f"https://{deployment_data['url']}"
            print(f"✅ Deployment triggered: {deployment_url}")
            return {
                "deployment_id": deployment_data["id"],
                "deployment_url": deployment_url,
                "status": deployment_data.get("readyState", "QUEUED"),
                "created_at": deployment_data.get("createdAt")
            }
        else:
            raise Exception(f"Failed to trigger deployment: {response.status_code} {response.text}")
    
    def get_deployment_status(self, deployment_id: str) -> Dict[str, Any]:
        """
        Check deployment status
        
        Args:
            deployment_id: Vercel deployment ID
        
        Returns:
            status_info: Dictionary with current status
        """
        url = f"{self.base_url}/v13/deployments/{deployment_id}"
        if self.team_id:
            url += f"?teamId={self.team_id}"
        
        response = requests.get(url, headers=self.headers)
        
        if response.status_code == 200:
            deployment_data = response.json()
            return {
                "status": deployment_data.get("readyState"),  # READY, ERROR, QUEUED, BUILDING
                "url": f"https://{deployment_data.get('url')}",
                "created_at": deployment_data.get("createdAt"),
                "ready_at": deployment_data.get("ready")
            }
        else:
            raise Exception(f"Failed to get deployment status: {response.status_code}")


# ==================== COMPLETE WORKFLOW ====================

def deploy_website_to_github_and_vercel(
    project_dir: str,
    site_name: str,
    description: str,
    github_token: str,
    vercel_token: str,
    github_org: str = "codexdominion",
    vercel_team_id: Optional[str] = None
) -> Dict[str, Any]:
    """
    Complete deployment workflow: Git → GitHub → Vercel
    
    Args:
        project_dir: Local path to generated Next.js project
        site_name: Website name (for repo and project names)
        description: Site description
        github_token: GitHub API token
        vercel_token: Vercel API token
        github_org: GitHub organization
        vercel_team_id: Vercel team ID (optional)
    
    Returns:
        deployment_info: Complete deployment details
    """
    print("=" * 70)
    print("GITHUB + VERCEL DEPLOYMENT WORKFLOW")
    print("=" * 70)
    print()
    
    # Step 1: Create GitHub repository
    print("📦 Step 1: Creating GitHub repository...")
    github = GitHubIntegration(github_token, github_org)
    repo_info = github.create_repository(
        repo_name=site_name,
        description=description,
        private=False
    )
    print()
    
    # Step 2: Push code to GitHub
    print("📤 Step 2: Pushing code to GitHub...")
    push_success = github.initialize_and_push(
        local_path=project_dir,
        repo_url=repo_info["ssh_url"],
        commit_message=f"Initial commit - {site_name} generated by CodexDominion"
    )
    if not push_success:
        raise Exception("Failed to push code to GitHub")
    print()
    
    # Step 3: Create Vercel project
    print("🚀 Step 3: Creating Vercel project...")
    vercel = VercelIntegration(vercel_token, vercel_team_id)
    project_info = vercel.create_project(
        project_name=repo_info["repo_name"],
        github_repo=f"{github_org}/{repo_info['repo_name']}",
        framework="nextjs"
    )
    print()
    
    # Step 4: Trigger production deployment
    print("🌐 Step 4: Triggering production deployment...")
    deployment_info = vercel.trigger_deployment(
        project_name=project_info["project_name"],
        production=True
    )
    print()
    
    # Step 5: Return complete info
    result = {
        "github": {
            "repo_name": repo_info["repo_name"],
            "repo_url": repo_info["repo_url"],
            "clone_url": repo_info["clone_url"]
        },
        "vercel": {
            "project_id": project_info["project_id"],
            "project_name": project_info["project_name"],
            "deployment_id": deployment_info["deployment_id"],
            "deployment_url": deployment_info["deployment_url"],
            "status": deployment_info["status"]
        },
        "summary": {
            "site_name": site_name,
            "live_url": deployment_info["deployment_url"],
            "source_code": repo_info["repo_url"],
            "deployment_status": "in_progress"
        }
    }
    
    print("=" * 70)
    print("✅ DEPLOYMENT INITIATED SUCCESSFULLY!")
    print("=" * 70)
    print(f"🌐 Live URL: {deployment_info['deployment_url']}")
    print(f"📦 Source: {repo_info['repo_url']}")
    print(f"⏳ Status: Deploying (check status in ~2 minutes)")
    print()
    
    return result


# ==================== ENVIRONMENT SETUP ====================

def setup_deployment_credentials():
    """
    Guide for setting up GitHub and Vercel API credentials
    
    Instructions printed to console
    """
    print("""
    ╔═══════════════════════════════════════════════════════════════════════╗
    ║        GITHUB + VERCEL DEPLOYMENT SETUP GUIDE                         ║
    ╚═══════════════════════════════════════════════════════════════════════╝
    
    STEP 1: GITHUB PERSONAL ACCESS TOKEN
    ------------------------------------
    1. Go to: https://github.com/settings/tokens/new
    2. Select scopes:
       ✅ repo (Full control of private repositories)
       ✅ workflow (Update GitHub Action workflows)
    3. Generate token
    4. Save to environment variable:
       export GITHUB_TOKEN="ghp_your_token_here"
    
    STEP 2: VERCEL API TOKEN
    -------------------------
    1. Go to: https://vercel.com/account/tokens
    2. Create new token
    3. Save to environment variable:
       export VERCEL_TOKEN="your_vercel_token_here"
    
    STEP 3: OPTIONAL - VERCEL TEAM ID
    ----------------------------------
    If deploying to a team:
    1. Go to: https://vercel.com/teams/YOUR_TEAM/settings
    2. Copy Team ID
    3. Save to environment variable:
       export VERCEL_TEAM_ID="team_xxx"
    
    STEP 4: TEST CREDENTIALS
    -------------------------
    Run: python github_vercel_integration.py --test
    
    ╔═══════════════════════════════════════════════════════════════════════╗
    ║  Once setup complete, all future deployments are fully automated!     ║
    ╚═══════════════════════════════════════════════════════════════════════╝
    """)


# ==================== EXAMPLE USAGE ====================

if __name__ == "__main__":
    import sys
    
    if "--test" in sys.argv:
        # Test credentials
        github_token = os.getenv("GITHUB_TOKEN")
        vercel_token = os.getenv("VERCEL_TOKEN")
        
        if not github_token:
            print("❌ GITHUB_TOKEN not set")
        else:
            print("✅ GITHUB_TOKEN found")
        
        if not vercel_token:
            print("❌ VERCEL_TOKEN not set")
        else:
            print("✅ VERCEL_TOKEN found")
    
    elif "--setup" in sys.argv:
        setup_deployment_credentials()
    
    else:
        # Example deployment
        print("Run with --setup for credential setup instructions")
        print("Run with --test to verify credentials")
