
substitutions:
  _DEPLOY_REGION: "us-central1"
  _SERVICE_NAME: "codex-dominion"
# Cloud Build configuration for Codex Dominion Treasury System
# Enhanced build process for complete treasury & dawn dispatch integration

steps:
  # Step 1: Build the Docker image matching your commands
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '--cache-from=gcr.io/$PROJECT_ID/codex-dashboard:latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/codex-dashboard:latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/codex-dashboard:$BUILD_ID'
      - '.'
    
  # Step 2: Push the versioned image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/codex-dashboard:$BUILD_ID']
    
  # Step 3: Push the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/codex-dashboard:latest']
    
  # Step 4: Deploy codex-dominion to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', '${_SERVICE_NAME}',
      '--image', 'us-central1-docker.pkg.dev/codex-dominion-production/codex-dominion/codex-dominion:latest',
      '--region', '${_DEPLOY_REGION}',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]
  
  # Step 5: Setup Cloud Scheduler for automated dawn dispatches
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Wait for service to be ready
        echo "🌅 Setting up automated dawn dispatch scheduler..."
        
        # Get deployed service URL
        SERVICE_URL=$$(gcloud run services describe codex-backend --region=us-central1 --format='value(status.url)')
        echo "Service URL: $$SERVICE_URL"
        
        # Enable Cloud Scheduler API
        gcloud services enable cloudscheduler.googleapis.com
        
        # Ensure App Engine app exists (required for Cloud Scheduler)
        if ! gcloud app describe --verbosity=error >/dev/null 2>&1; then
          echo "Creating App Engine app for Cloud Scheduler..."
          gcloud app create --region=us-central1
        fi
        
        # Create or update dawn dispatch scheduler job
        if gcloud scheduler jobs describe dawn-dispatch --location=us-central1 >/dev/null 2>&1; then
          echo "Updating existing scheduler job..."
          gcloud scheduler jobs update http dawn-dispatch \
            --location=us-central1 \
            --schedule="0 6 * * *" \
            --uri="$$SERVICE_URL/dawn" \
            --http-method=POST \
            --time-zone="America/New_York"
        else
          echo "Creating new scheduler job..."
          gcloud scheduler jobs create http dawn-dispatch \
            --location=us-central1 \
            --schedule="0 6 * * *" \
            --uri="$$SERVICE_URL/dawn" \
            --http-method=POST \
            --time-zone="America/New_York" \
            --description="Automated daily dawn dispatch for Codex Dominion treasury system"
        fi
        
        echo "✅ Dawn dispatch scheduler configured successfully!"
        echo "⏰ Daily dispatches will execute at 6:00 AM Eastern Time"

# Images to be stored in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/codex-dashboard:latest'
  - 'gcr.io/$PROJECT_ID/codex-dashboard:$BUILD_ID'

# Build options
options:
  # Use a more powerful machine for faster builds
  machineType: 'E2_HIGHCPU_8'
  # Enable logging for debugging
  logging: CLOUD_LOGGING_ONLY
  # Disk size for larger builds
  diskSizeGb: 100

# Timeout for the build (30 minutes)
timeout: 1800s



# Tags for organization and tracking
tags:
  - 'codex-dominion'
  - 'treasury-system'
  - 'dawn-dispatch'
  - 'production'
  - 'cloud-run'