apiVersion: v1
kind: Namespace
metadata:
  name: codex
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: codex-config
  namespace: codex
data:
  APP_ENV: production
  API_URL: https://codexdominion.app/api
---
apiVersion: v1
kind: Secret
metadata:
  name: codex-secrets
  namespace: codex
type: Opaque
data:
  DB_PASSWORD: eW91cnBhc3N3b3Jk
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codex-web
  namespace: codex
spec:
  replicas: 3
  selector:
    matchLabels:
      app: codex-web
  template:
    metadata:
      labels:
        app: codex-web
    spec:
      containers:
        - name: codex-web
          image: gcr.io/codex-dominion-production/codex-web:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: codex-config
            - secretRef:
                name: codex-secrets
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  name: codex-service
  namespace: codex
spec:
  selector:
    app: codex-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: codex-ingress
  namespace: codex
  annotations:
    networking.gke.io/managed-certificates: codex-cert
spec:
  rules:
    - host: codexdominion.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: codex-service
                port:
                  number: 80
