apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: observability
  labels:
    grafana_datasource: 'true'
data:
  prometheus-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service.observability.svc.cluster.local:9090
        isDefault: true
        editable: true
