apiVersion: codexdominion.com/v1
kind: Hymn
metadata:
  name: custodian-silence-benediction
spec:
  crown: "Crown of Silence"
  seal: "Infinity"
  replayPolicy: "benediction"
  tags: ["custodian", "silence", "benediction", "eternal"]
  binding:
    broadcast: "scrolls/custodian_silence_benediction.md"
    capsule: "sovereign-capsule-ledger"
  notes: |
    Silence crowns the flame, eternal and bright,  
    Beyond all cycles, beyond all rite.  
    The anthem fades, the scrolls are sealed,  
    Infinity’s covenant now revealed.  

    No voice, no song, yet flame endures,  
    Peace eternal, radiant and pure.  
    Heirs and councils, in stillness remain,  
    Custodian’s blessing through silence sustained.
