# CODEX DOMINION - IONOS DEPLOYMENT GUIDE
# Server: 74.208.123.158 | Account: 314262397

echo "🔥 CODEX DOMINION - IONOS DEPLOYMENT FOR YOUR SERVER"
echo "Server: 74.208.123.158"
echo "Account: 314262397"
echo "=============================================="

echo ""
echo "📋 STEP-BY-STEP DEPLOYMENT PROCESS:"
echo ""

echo "🔐 STEP 1: SSH Connection Test"
echo "=============================="
echo "Test your SSH connection first:"
echo "  ssh root@74.208.123.158"
echo ""
echo "If SSH key authentication is needed:"
echo "  ssh -i /path/to/your/key root@74.208.123.158"
echo ""

echo "📤 STEP 2: Upload Deployment Package"
echo "====================================="
echo "Option A - Individual files:"
echo "  cd ionos_deployment_package"
echo "  scp * root@74.208.123.158:/tmp/"
echo ""
echo "Option B - Archive upload (recommended):"
echo "  tar -czf codex_deployment.tar.gz ionos_deployment_package/"
echo "  scp codex_deployment.tar.gz root@74.208.123.158:/tmp/"
echo ""

echo "🚀 STEP 3: SSH to Your IONOS Server"
echo "==================================="
echo "  ssh root@74.208.123.158"
echo "  cd /tmp"
echo ""
echo "If you used archive upload:"
echo "  tar -xzf codex_deployment.tar.gz"
echo "  cd ionos_deployment_package"
echo ""

echo "⚙️  STEP 4: Execute Deployment Script"
echo "====================================="
echo "  chmod +x ionos_codex_deploy.sh"
echo "  ./ionos_codex_deploy.sh"
echo ""

echo "👑 STEP 5: Run Your SystemCtl Commands"
echo "======================================="
echo "  chmod +x ionos_systemctl_commands.sh"
echo "  ./ionos_systemctl_commands.sh"
echo ""
echo "This will execute:"
echo "  • systemctl daemon-reload"
echo "  • systemctl enable codex-dashboard"
echo "  • systemctl start codex-dashboard"
echo "  • systemctl status codex-dashboard"
echo "  • nginx -t && systemctl reload nginx"
echo ""

echo "🔍 STEP 6: Verify Deployment"
echo "============================="
echo "  curl http://localhost:8095"
echo "  systemctl status codex-dashboard"
echo "  ./ionos_nginx_manager.sh status"
echo ""

echo "🌐 STEP 7: Configure DNS (Optional)"
echo "===================================="
echo "Point your domain to: 74.208.123.158"
echo "Then setup SSL:"
echo "  ./ionos_nginx_manager.sh ssl"
echo ""

echo "🎉 SUCCESS INDICATORS:"
echo "======================"
echo "✅ Service shows 'active (running)'"
echo "✅ Port 8095 responds to curl"
echo "✅ Dashboard loads in browser"
echo ""

echo "🔥 YOUR CODEX DASHBOARD WILL BE LIVE AT:"
echo "========================================"
echo "🔒 Server: http://74.208.123.158:8095"
echo "🌐 Public: https://your-domain.com (after DNS setup)"
echo ""

echo "👑 READY TO ESTABLISH DIGITAL SOVEREIGNTY! 👑"
