apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
  namespace: codex-dominion
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      # Ensure 'regcred' secret exists in this namespace
      # Ensure 'dominion-config' ConfigMap and 'dominion-secrets' Secret exist
      imagePullSecrets:
        - name: regcred
      initContainers:
        - name: setup-script
          image: busybox
          command: ['sh', '-c', 'echo Hello, setup!']
      containers:
        - name: orchestrator
          image: ghcr.io/your-org/orchestrator:latest
          ports:
            - containerPort: 8000
          # Service exposes port 80, mapped to container port 8000
          envFrom:
            - configMapRef:
                name: dominion-config
            - secretRef:
                name: dominion-secrets
          lifecycle:
            postStart:
              exec:
                command: ['sh', '-c', 'echo PostStart hook executed']
            preStop:
              exec:
                command: ['sh', '-c', 'echo PreStop hook executed']
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            # Ensure /healthz endpoint exists in your app
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            # Ensure /healthz endpoint exists in your app
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: '50m'
              memory: '64Mi'
            limits:
              cpu: '250m'
              memory: '256Mi'
---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator
  namespace: codex-dominion
spec:
  selector:
    app: orchestrator
  ports:
    - port: 80
      targetPort: 8000
      name: http
