#!/usr/bin/env python3
"""
Test the Cloud Storage archiving functionality for Codex Dominion
"""
import os
import sys

# Add the codex_capsules directory to the path
sys.path.append(os.path.join(os.path.dirname(__file__), "codex_capsules"))

import datetime

from storage_archiver import (archive_bulletin, archive_snapshot,
                              list_capsule_artifacts)


def test_archiving():
    """Test the archiving functions with sample data"""

    print("🗄️ Testing Codex Dominion Cloud Storage Archiving...")
    print("=" * 60)

    try:
        # Test snapshot archiving
        print("\n📊 Testing Snapshot Archiving...")

        sample_snapshot = {
            "execution_id": f"exec_{datetime.datetime.utcnow().strftime('%Y%m%d_%H%M%S')}",
            "capsule_info": {
                "slug": "signals-daily",
                "version": "1.0.0",
                "execution_mode": "scheduled",
            },
            "status": "success",
            "metrics": {
                "start_time": datetime.datetime.utcnow().isoformat(),
                "duration_seconds": 42.5,
                "items_processed": 127,
                "signals_generated": 8,
            },
            "outputs": [
                "market_signal_bullish",
                "sentiment_positive",
                "volume_increasing",
                "volatility_moderate",
            ],
            "sovereignty_score": 0.85,
        }

        snapshot_uri = archive_snapshot(sample_snapshot, "signals-daily")
        print(f"✅ Snapshot archived successfully!")
        print(f"📍 URI: {snapshot_uri}")

        # Test bulletin archiving
        print("\n📝 Testing Bulletin Archiving...")

        current_time = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")
        sample_bulletin = f"""# 🌅 Dawn Sovereignty Bulletin

## 📊 Operational Status: **SOVEREIGN**

**Date:** {current_time} UTC  
**Capsule:** Dawn Dispatch  
**Version:** 1.0.0  

---

### 🎯 Key Performance Indicators

| Metric | Value | Status |
|--------|-------|---------|
| System Health | 100% | 🟢 Optimal |
| Active Capsules | 5 | 🟢 Full Deployment |
| Daily Executions | 2 | 🟢 Scheduled |
| Sovereignty Index | 0.85 | 🟢 High |

### 🔄 Recent Activities

- ✅ **Dawn Dispatch** completed successfully at 06:00 UTC
- ✅ **Signals Processing** running optimally  
- ✅ **Database Operations** performing within parameters
- ⏰ **Treasury Audit** scheduled for month-end

### 🎲 Operational Insights

**Signals Engine:** Processing market data with 94% accuracy  
**Storage Systems:** Versioned artifacts maintaining full lineage  
**Security Posture:** All credentials secured via Secret Manager  

### 🏆 Sovereignty Declaration

**The Codex Dominion maintains full operational sovereignty.**  
All systems are autonomous, self-sustaining, and operating at peak efficiency.

---

*This bulletin was automatically generated by the Dawn Dispatch capsule.*  
*For detailed metrics, consult the capsule runs database.*  

**🌟 Long live the Codex Dominion! 👑**
"""

        bulletin_uri = archive_bulletin(sample_bulletin, "dawn")
        print(f"✅ Bulletin archived successfully!")
        print(f"📍 URI: {bulletin_uri}")

        # Test artifact listing
        print(f"\n📋 Testing Artifact Listing...")

        artifacts = list_capsule_artifacts("signals-daily", limit=3)
        print(f"📊 Found {len(artifacts)} artifacts for 'signals-daily':")

        for i, artifact in enumerate(artifacts, 1):
            print(f"   {i}. {artifact['name']}")
            print(f"      📅 Created: {artifact['created']}")
            print(f"      📏 Size: {artifact['size']} bytes")
            print(f"      🔗 URI: {artifact['uri']}")

        print(f"\n🎉 All archiving tests completed successfully!")
        print(f"💾 Cloud Storage Bucket: codex-artifacts-codex-dominion-prod")
        print(f"🔗 Versioning: Enabled")
        print(f"🗂️ Organization: Structured by type/capsule/date")

        return True

    except Exception as e:
        print(f"❌ Archiving test failed: {e}")
        return False


if __name__ == "__main__":
    test_archiving()
