# core/publisher.py (Extended from Cycle 3)
import json
from datetime import datetime
from pathlib import Path


def publish_html(page_json="love_lab_page.json", output="public/page.html"):
    """Extended HTML publisher with enhanced component support"""
    data = json.loads(Path(page_json).read_text())

    # Enhanced HTML template with CSS and metadata
    html = [
        "<!DOCTYPE html>",
        "<html lang='en'>",
        "<head>",
        "    <meta charset='UTF-8'>",
        "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>",
        "    <title>Codex Dominion Page</title>",
        "    <style>",
        "        body { font-family: Arial, sans-serif; margin: 0; padding: 20px; }",
        "        section { margin: 20px 0; padding: 20px; }",
        "        .hero { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; text-align: center; }",
        "        .features ul { list-style: none; padding: 0; }",
        "        .features li { padding: 10px; margin: 5px 0; background: #f5f5f5; border-radius: 5px; }",
        "        .gallery img { max-width: 100%; height: auto; margin: 10px; }",
        "        .form { background: #f9f9f9; padding: 20px; border-radius: 8px; }",
        "        .footer { text-align: center; color: #666; border-top: 1px solid #eee; padding-top: 20px; }",
        "    </style>",
        "</head>",
        "<body>",
    ]

    # Process each block with enhanced rendering
    for block in data["blocks"]:
        if block["type"] == "Hero":
            c = block["config"]
            html.append(f"    <section class='hero'>")
            html.append(f"        <h1>{c.get('title', 'Sovereign headline')}</h1>")
            html.append(f"        <p>{c.get('subtitle', 'Warm subcopy')}</p>")
            html.append(
                f"        <a href='#' style='background: rgba(255,255,255,0.2); padding: 10px 20px; text-decoration: none; color: white; border-radius: 5px;'>{c.get('cta', 'Witness')}</a>"
            )
            html.append(f"    </section>")

        elif block["type"] == "Features":
            c = block["config"]
            html.append(f"    <section class='features'>")
            html.append(f"        <h2>Features</h2>")
            html.append(f"        <ul>")
            for item in c.get("items", []):
                html.append(f"            <li>✨ {item}</li>")
            html.append(f"        </ul>")
            html.append(f"    </section>")

        elif block["type"] == "Gallery":
            c = block["config"]
            html.append(f"    <section class='gallery'>")
            html.append(f"        <h2>Gallery</h2>")
            for img in c.get("images", []):
                html.append(f"        <img src='{img}' alt='Gallery image' />")
            html.append(f"    </section>")

        elif block["type"] == "Form":
            c = block["config"]
            html.append(f"    <section class='form'>")
            html.append(f"        <h2>Contact</h2>")
            html.append(
                f"        <form action='{c.get('action', '/submit')}' method='POST'>"
            )
            for field in c.get("fields", []):
                html.append(
                    f"            <p><label>{field}: <input type='text' name='{field.lower()}' required></label></p>"
                )
            html.append(f"            <button type='submit'>Submit</button>")
            html.append(f"        </form>")
            html.append(f"    </section>")

        elif block["type"] == "Footer":
            c = block["config"]
            html.append(f"    <footer class='footer'>")
            html.append(
                f"        <p>{c.get('text', 'Codex Eternum')} • Generated by Codex Dominion Suite</p>"
            )
            html.append(
                f"        <p><small>Published: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</small></p>"
            )
            html.append(f"    </footer>")

    html.extend(["</body>", "</html>"])

    # Ensure output directory exists
    Path(output).parent.mkdir(parents=True, exist_ok=True)
    Path(output).write_text("\n".join(html), encoding="utf-8")

    return output


def publish_batch(input_dir="pages/", output_dir="public/"):
    """Batch publish multiple pages"""
    input_path = Path(input_dir)
    output_path = Path(output_dir)

    published_files = []

    if input_path.exists():
        for json_file in input_path.glob("*.json"):
            output_file = output_path / f"{json_file.stem}.html"
            result = publish_html(str(json_file), str(output_file))
            published_files.append(result)

    return published_files
