export default function Footer() {
  return (
    <footer className="bg-gray-900 text-white py-8 mt-16">
      <div className="container mx-auto px-4">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          <div>
            <h3 className="text-xl font-heading font-bold mb-4">Demo Site</h3>
            <p className="text-gray-400">Testing Steps 6-10</p>
          </div>
          <div>
            <h4 className="font-heading font-bold mb-4">Quick Links</h4>
            <div className="flex flex-col gap-2">
              <a href="/" className="hover:text-primary transition-colors">Home</a>
            <a href="/about" className="hover:text-primary transition-colors">About</a>
            </div>
          </div>
          <div>
            <h4 className="font-heading font-bold mb-4">Contact</h4>
            <p className="text-gray-400">info@example.com</p>
          </div>
        </div>
        <div className="border-t border-gray-800 mt-8 pt-8 text-center text-gray-400">
          <p>&copy; 2025 Demo Site. All rights reserved.</p>
          <p className="text-sm mt-2">Generated by Codex Dominion</p>
        </div>
      </div>
    </footer>
  )
}
