/**
 * Node.js API Route Template - Express + TypeScript
 * Generated by Codex Dominion Autonomous Coding System
 */

import { Router, Request, Response, NextFunction } from 'express';
import { body, param, query, validationResult } from 'express-validator';
import { authenticate, authorize } from '../middleware/auth';
import { rateLimit } from '../middleware/rateLimit';
import { {{SERVICE_NAME}} } from '../services/{{SERVICE_FILE}}';
import { logger } from '../utils/logger';
import { AppError } from '../utils/errors';

const router = Router();
const service = new {{SERVICE_NAME}}();

/**
 * @route   GET /api/{{ROUTE_PATH}}
 * @desc    {{GET_DESCRIPTION}}
 * @access  {{GET_ACCESS_LEVEL}}
 */
router.get(
  '/{{ROUTE_PATH}}',
  authenticate,
  authorize(['{{REQUIRED_ROLES}}']),
  rateLimit({ maxRequests: 100, windowMs: 60000 }),
  [
    {{GET_VALIDATION}}
  ],
  async (req: Request, res: Response, next: NextFunction) => {
    try {
      // Validation
      const errors = validationResult(req);
      if (!errors.isEmpty()) {
        throw new AppError('Validation failed', 400, errors.array());
      }

      // Business logic
      const result = await service.{{GET_METHOD}}({{GET_PARAMS}});

      // Audit log
      logger.info('{{GET_METHOD}} executed', {
        user: req.user?.id,
        params: req.params,
        result: result
      });

      // Response
      res.status(200).json({
        success: true,
        data: result,
        timestamp: new Date().toISOString()
      });
    } catch (error) {
      next(error);
    }
  }
);

/**
 * @route   POST /api/{{ROUTE_PATH}}
 * @desc    {{POST_DESCRIPTION}}
 * @access  {{POST_ACCESS_LEVEL}}
 */
router.post(
  '/{{ROUTE_PATH}}',
  authenticate,
  authorize(['{{REQUIRED_ROLES}}']),
  rateLimit({ maxRequests: 50, windowMs: 60000 }),
  [
    {{POST_VALIDATION}}
  ],
  async (req: Request, res: Response, next: NextFunction) => {
    try {
      // Validation
      const errors = validationResult(req);
      if (!errors.isEmpty()) {
        throw new AppError('Validation failed', 400, errors.array());
      }

      // Business logic
      const result = await service.{{POST_METHOD}}(req.body);

      // Audit log
      logger.info('{{POST_METHOD}} executed', {
        user: req.user?.id,
        body: req.body,
        result: result
      });

      // Response
      res.status(201).json({
        success: true,
        data: result,
        timestamp: new Date().toISOString()
      });
    } catch (error) {
      next(error);
    }
  }
);

/**
 * @route   PUT /api/{{ROUTE_PATH}}/:id
 * @desc    {{PUT_DESCRIPTION}}
 * @access  {{PUT_ACCESS_LEVEL}}
 */
router.put(
  '/{{ROUTE_PATH}}/:id',
  authenticate,
  authorize(['{{REQUIRED_ROLES}}']),
  [
    param('id').isUUID().withMessage('Invalid ID format'),
    {{PUT_VALIDATION}}
  ],
  async (req: Request, res: Response, next: NextFunction) => {
    try {
      const errors = validationResult(req);
      if (!errors.isEmpty()) {
        throw new AppError('Validation failed', 400, errors.array());
      }

      const result = await service.{{PUT_METHOD}}(req.params.id, req.body);

      logger.info('{{PUT_METHOD}} executed', {
        user: req.user?.id,
        id: req.params.id,
        body: req.body
      });

      res.status(200).json({
        success: true,
        data: result,
        timestamp: new Date().toISOString()
      });
    } catch (error) {
      next(error);
    }
  }
);

/**
 * @route   DELETE /api/{{ROUTE_PATH}}/:id
 * @desc    {{DELETE_DESCRIPTION}}
 * @access  {{DELETE_ACCESS_LEVEL}}
 */
router.delete(
  '/{{ROUTE_PATH}}/:id',
  authenticate,
  authorize(['{{REQUIRED_ROLES}}']),
  [
    param('id').isUUID().withMessage('Invalid ID format')
  ],
  async (req: Request, res: Response, next: NextFunction) => {
    try {
      const errors = validationResult(req);
      if (!errors.isEmpty()) {
        throw new AppError('Validation failed', 400, errors.array());
      }

      await service.{{DELETE_METHOD}}(req.params.id);

      logger.info('{{DELETE_METHOD}} executed', {
        user: req.user?.id,
        id: req.params.id
      });

      res.status(204).send();
    } catch (error) {
      next(error);
    }
  }
);

export default router;
