apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: codex-core
  namespace: codex
spec:
  replicas: 3
  selector:
    matchLabels:
      app: codex-core
  template:
    metadata:
      labels:
        app: codex-core
    spec:
      containers:
        - name: codex-core
          image: ghcr.io/your-org/codex-core:v1.0.0
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8081
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8081
            initialDelaySeconds: 10
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {duration: 10m}
        - setWeight: 50
        - pause: {duration: 10m}
      trafficRouting:
        nginx:
          stableIngress: codex-core-ingress