apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: orchestrator
  namespace: codex
spec:
  replicas: 3
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
        - name: orchestrator
          image: ghcr.io/your-org/codex-orchestrator:prod
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: prod-values
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {duration: 10m}
        - setWeight: 50
        - pause: {duration: 10m}
      trafficRouting:
        nginx:
          stableIngress: orchestrator-ingress