name: Setup Constellation
description: Standard setup for CODEX-DOMINION workflows

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'npm'

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install base tools
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install yamllint pylint bandit
        npm i -D eslint prettier
        sudo apt-get update && sudo apt-get install -y jq shellcheck
        curl -sL https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo gpg --dearmor -o /usr/share/keyrings/trivy.gpg
        echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb stable main" | sudo tee /etc/apt/sources.list.d/trivy.list
        sudo apt-get update && sudo apt-get install -y trivy
inputs:
  node_version:
    description: Node version
    required: true
  python_version:
    description: Python version
    required: true
