apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: engine01
  namespace: codex
spec:
  replicas: 1
  strategy:
    canary:
      stableService: engine01-stable
      canaryService: engine01-canary
      trafficRouting:
        nginx:
          stableIngress: engine01-ingress
      steps:
      - setWeight: 50
      - pause: { duration: 120 }
      - setWeight: 100
      analysis:
        templates:
        - templateName: nginx-success-rate
        args:
        - name: service-name
          value: engine01
        startingStep: 1
  selector:
    matchLabels:
      app: engine01
  template:
    metadata:
      labels:
        app: engine01
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: engine01
        image: ghcr.io/your-org/engine01:v1.0.0
        ports:
        - name: http-metrics
          containerPort: 8080
        readinessProbe:
          httpGet: { path: /health/ready, port: 8080 }
        livenessProbe:
          httpGet: { path: /health/live, port: 8080 }
---
apiVersion: v1
kind: Service
metadata:
  name: engine01-stable
  namespace: codex
spec:
  selector: { app: engine01 }
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: engine01-canary
  namespace: codex
spec:
  selector: { app: engine01 }
  ports:
  - name: http
    port: 8080
    targetPort: 8080
