apiVersion: apps/v1
kind: Deployment
metadata:
  name: codex-core
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: codex-core
          resources:
            requests:
              cpu: '500m'
              memory: '1Gi'
            limits:
              cpu: '2000m'
              memory: '2Gi'
