apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: orchestrator
          resources:
            requests:
              cpu: '500m'
              memory: '1Gi'
            limits:
              cpu: '2000m'
              memory: '2Gi'
          env:
            - name: ENV
              value: 'prod'
