apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: codex-core
spec:
  replicas: 2
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause: { duration: 90 }
        - setWeight: 100
  selector:
    matchLabels: { app: codex-core }
  template:
    metadata:
      labels: { app: codex-core }
    spec:
      containers:
        - name: codex-core
          image: ghcr.io/your-org/codex-core:v1.0.0
          ports: [{ containerPort: 8081 }]
          env:
            - name: ORCHESTRATOR_HOST
              value: "codex-orchestrator"
            - name: ORCHESTRATOR_PORT
              value: "8000"
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "2000m"
              memory: "2Gi"
          readinessProbe:
            httpGet: { path: /health/ready, port: 8081 }
          livenessProbe:
            httpGet: { path: /health/live, port: 8081 }
