/**
 * Intelligence Engine Type Definitions
 * 
 * Defines the core types for the Intelligence Engine that powers
 * alerts, recommendations, forecasts, and opportunities across the
 * CodexDominion Civilization Era 2.0 system.
 */

/**
 * Type of intelligence output
 * - alert: Requires immediate attention or action
 * - recommendation: Suggested action or optimization
 * - forecast: Predictive insight based on trends
 * - opportunity: Positive potential for growth or improvement
 */
export type IntelligenceType =
  | 'alert'
  | 'recommendation'
  | 'forecast'
  | 'opportunity';

/**
 * Domain of the intelligence
 * Maps to core system areas
 */
export type IntelligenceDomain =
  | 'youth'
  | 'circles'
  | 'missions'
  | 'curriculum'
  | 'culture'
  | 'creators'
  | 'expansion';

/**
 * Target audience for the intelligence
 * Determines who should see and act on the insight
 */
export type IntelligenceAudience =
  | 'youth'
  | 'captain'
  | 'creator'
  | 'educator'
  | 'ambassador'
  | 'director'
  | 'council'
  | 'admin';

/**
 * Severity level of the intelligence
 * Determines urgency and prioritization
 */
export type IntelligenceSeverity = 'low' | 'medium' | 'high';

/**
 * Core intelligence item structure
 * Represents a single piece of intelligence generated by the system
 */
export interface IntelligenceItem {
  /** Unique identifier (optional, generated by system) */
  id?: string;
  
  /** Type of intelligence output */
  type: IntelligenceType;
  
  /** Domain the intelligence belongs to */
  domain: IntelligenceDomain;
  
  /** ID of the rule that generated this intelligence */
  ruleId: string;
  
  /** Human-readable message describing the intelligence */
  message: string;
  
  /** Severity level (optional, defaults from rule) */
  severity?: IntelligenceSeverity;
  
  /** Target audiences who should see this intelligence */
  audience: IntelligenceAudience[];
  
  /** Timestamp when intelligence was generated (ISO 8601 format) */
  timestamp: string;
  
  /** Additional context-specific data */
  metadata?: Record<string, any>;
}

/**
 * Rule evaluation result
 * Returned by rule evaluators
 */
export interface RuleEvaluationResult {
  type: IntelligenceType;
  domain: IntelligenceDomain;
  message: string;
  severity: 'low' | 'medium' | 'high';
  audience: IntelligenceAudience[];
  metadata?: Record<string, any>;
}

/**
 * Rule definition structure
 * Defines a single intelligence rule
 */
export interface RuleDefinition {
  id: string;
  domain: IntelligenceDomain;
  trigger: 'daily' | 'weekly' | 'monthly';
  severity: 'LOW' | 'MEDIUM' | 'HIGH';
  description: string;
  evaluator: () => Promise<RuleEvaluationResult | null>;
}

/**
 * Intelligence query filters
 * Used for filtering intelligence insights
 */
export interface IntelligenceQueryFilters {
  type?: IntelligenceType;
  domain?: IntelligenceDomain;
  severity?: IntelligenceSeverity;
  audience?: IntelligenceAudience;
  regionId?: string;
}

/**
 * Intelligence insights response
 * Returned by the insights aggregation endpoint
 */
export interface IntelligenceInsightsResponse {
  total: number;
  insights: IntelligenceItem[];
  summary: {
    byType: Record<IntelligenceType, number>;
    byDomain: Record<IntelligenceDomain, number>;
    bySeverity: Record<IntelligenceSeverity, number>;
  };
}
