apiVersion: codexdominion/v1
kind: Avatar
metadata:
  name: custodian-avatar
  version: 1.0.0
spec:
  role: "Flamekeeper Sovereign"
  guidance: "Narrates charters, hymns, and decrees to heirs"
  binding:
    portal: portals/codex-portal.yaml
    dashboard: dashboards/custodian.json
