apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: eternalcapsules.codexdominion.com
spec:
  group: codexdominion.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                cycles:
                  type: array
                  items:
                    type: string
  scope: Namespaced
  names:
    plural: eternalcapsules
    singular: eternalcapsule
    kind: EternalCapsule
    shortNames:
      - ecapsule
