apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: orchestrator
spec:
  replicas: 3
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: { duration: 60 }
        - setWeight: 50
        - pause: { duration: 120 }
        - setWeight: 100
      analysis:
        templates:
          - templateName: orchestrator-success-ratio
        interval: 30
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
        - name: orchestrator
          image: ghcr.io/your-org/codex-orchestrator:prod
          resources:
            requests:
              cpu: '500m'
              memory: '1Gi'
            limits:
              cpu: '2000m'
              memory: '2Gi'
          env:
            - name: ENV
              value: 'prod'
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: orchestrator-success-ratio
spec:
  args: []
  metrics:
    - name: orchestrator-success-ratio
      provider:
        prometheus:
          address: http://prometheus:9090
          query: |
            sum(rate(http_requests_total{job=\"orchestrator\",status=~\"2..\"}[5m])) /
            sum(rate(http_requests_total{job=\"orchestrator\"}[5m])
      successCondition: result[0] >= 0.99
      failureCondition: result[0] < 0.95
