apiVersion: v1
kind: Service
metadata:
  name: engine01
spec:
  selector:
    app: engine01
  ports:
    - port: 8080
      targetPort: 8080
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: engine02
spec:
  selector:
    app: engine02
  ports:
    - port: 8082
      targetPort: 8082
      name: http
