---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine01
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: engine01
          image: ghcr.io/your-org/engine01:dev
          resources:
            requests:
              cpu: '50m'
              memory: '64Mi'
            limits:
              cpu: '250m'
              memory: '256Mi'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine02
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: engine02
          image: ghcr.io/your-org/engine02:dev
          resources:
            requests:
              cpu: '50m'
              memory: '64Mi'
            limits:
              cpu: '250m'
              memory: '256Mi'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine03
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: engine03
          image: ghcr.io/your-org/engine03:dev
          resources:
            requests:
              cpu: '50m'
              memory: '64Mi'
            limits:
              cpu: '250m'
              memory: '256Mi'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine04
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: engine04
          image: ghcr.io/your-org/engine04:dev
          resources:
            requests:
              cpu: '50m'
              memory: '64Mi'
            limits:
              cpu: '250m'
              memory: '256Mi'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine05
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: engine05
          image: ghcr.io/your-org/engine05:dev
          resources:
            requests:
              cpu: '50m'
              memory: '64Mi'
            limits:
              cpu: '250m'
              memory: '256Mi'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine06
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: engine06
          image: ghcr.io/your-org/engine06:dev
          resources:
            requests:
              cpu: '50m'
              memory: '64Mi'
            limits:
              cpu: '250m'
              memory: '256Mi'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine07
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: engine07
          image: ghcr.io/your-org/engine07:dev
          resources:
            requests:
              cpu: '50m'
              memory: '64Mi'
            limits:
              cpu: '250m'
              memory: '256Mi'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine08
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: engine08
          image: ghcr.io/your-org/engine08:dev
          resources:
            requests:
              cpu: '50m'
              memory: '64Mi'
            limits:
              cpu: '250m'
              memory: '256Mi'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine09
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: engine09
          image: ghcr.io/your-org/engine09:dev
          resources:
            requests:
              cpu: '50m'
              memory: '64Mi'
            limits:
              cpu: '250m'
              memory: '256Mi'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine10
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: engine10
          image: ghcr.io/your-org/engine10:dev
          resources:
            requests:
              cpu: '50m'
              memory: '64Mi'
            limits:
              cpu: '250m'
              memory: '256Mi'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine11
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: engine11
          image: ghcr.io/your-org/engine11:dev
          resources:
            requests:
              cpu: '50m'
              memory: '64Mi'
            limits:
              cpu: '250m'
              memory: '256Mi'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine12
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: engine12
          image: ghcr.io/your-org/engine12:dev
          resources:
            requests:
              cpu: '50m'
              memory: '64Mi'
            limits:
              cpu: '250m'
              memory: '256Mi'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine13
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: engine13
          image: ghcr.io/your-org/engine13:dev
          resources:
            requests:
              cpu: '50m'
              memory: '64Mi'
            limits:
              cpu: '250m'
              memory: '256Mi'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine14
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: engine14
          image: ghcr.io/your-org/engine14:dev
          resources:
            requests:
              cpu: '50m'
              memory: '64Mi'
            limits:
              cpu: '250m'
              memory: '256Mi'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine15
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: engine15
          image: ghcr.io/your-org/engine15:dev
          resources:
            requests:
              cpu: '50m'
              memory: '64Mi'
            limits:
              cpu: '250m'
              memory: '256Mi'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine16
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: engine16
          image: ghcr.io/your-org/engine16:dev
          resources:
            requests:
              cpu: '50m'
              memory: '64Mi'
            limits:
              cpu: '250m'
              memory: '256Mi'
