apiVersion: apps/v1
kind: Deployment
metadata:
  name: codex-core
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: codex-core
          resources:
            requests:
              cpu: '100m'
              memory: '256Mi'
            limits:
              cpu: '500m'
              memory: '512Mi'
